name: Tự Động Cập Nhật Link Bóng Đá

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kiểm tra mã nguồn
      uses: actions/checkout@v4

    - name: Thiết lập Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cài đặt thư viện cần thiết
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Chạy script lấy link
      run: python scraper.py

    - name: Tự động lưu file mới lên GitHub
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        # Kiểm tra nếu có file thì mới add để không bao giờ bị lỗi pathspec
        if [ -f bongda.m3u ]; then
          git add bongda.m3u
          git commit -m "Bot tự động cập nhật danh sách trận đấu" || echo "Không có thay đổi"
          git push
        fi
